<?php
namespace CAG\T3footnotes\Controller;

use TYPO3\CMS\Extbase\Mvc\Controller\ActionController;
use Psr\Http\Message\ResponseInterface;
/***
 *
 * This file is part of the "Fuss" Extension for TYPO3 CMS.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 *
 *  (c) 2019 
 *
 ***/
/**
 * FootnoteController
 */
class FootnoteController extends ActionController
{

    /**
     * action list
     * 
     * @return void
     */
    public function listAction(): ResponseInterface
    {
        // Action to render static container für t3footnotes generated by contentPostProc-cached Hook
        return $this->htmlResponse();
    }


}
